### ISSUE TITLE
AudioSink task list

### ISSUE THREAD

**Issue by sockheadrps** [Beaux44/rpaudio#1]
### AudioSink Python Methods and Attributes

- [x] **`AudioSink` Class**
  - [x] **attribute : `metadata`**: Returns audio metadata as a dictionary.
  - [x] **attribute: `is_playing`**: Checks if the audio is currently playing.
  - [x] **Method: `load_audio`**: Loads an audio file into the sink.
  - [x] **Method: `play`**: Starts playing the loaded audio.
  - [x] **Method: `pause`**: Pauses the currently playing audio.
  - [x] **Method: `stop`**: Stops the audio and resets the sink.
  - [x] **Method: `empty`**: Checks if the sink has finished playing all audio.
  - [x] **Method: `cancel_callback`**: Cancels the completion callback for the current audio.
  - [x] ** Method `seek`: Seeks to audio playback position
  - [x] ** attribute `get_position` Gets current audio position
